all:
	cd acpc/src;  make clean; make;
	cd proto; make;
	cd util/src;  make clean; make;
	cd script/src;  make clean; make;
	cd network/src; make clean; make;
	cd frame/src; make clean; make;
	cd shstd; make clean; make;
	cd public/src; make clean; make;
	cd r3c/src; make clean; make;
	cd version; make clean; make;
	#cd ;  make -f makefile.std;
	#cd src;  make -f makefile.ldap;
	

#clean:
#	cd acpc/src; make clean ;
#	cd frame/src; make clean ;
#	cd  shstd; make clean ;

